### ISSUE TITLE
Check what the new Facebook ban to the use of Messenger for healthcare providers means for the chatbot use case

### ISSUE THREAD

**Issue by nekron** [instedd/active-monitoring#116]
Check the implications of https://developers.facebook.com/policy#messengerplatform section 17.8.3 which states:
> Healthcare: Don't use Messenger to facilitate direct conversations between people and healthcare providers or to send or collect any patient data obtained from healthcare providers.

**Comment by edjez** [comment]
Seems OK. As long as
-  user opts in to 'subscription' messaging e.g. somewhere it says 'this will help you monitor for XX days' 
- We don't use the bot to directly facade a human healthcare provider (which we don't)
- We don't use the bot to send data about that particular patient from a licensed healthcare provider; 
- We don't use the bot to request data from the patient that was given to them by a licensed healthcare provider.  (eg ask for a diagnosis, ..however we'd need to be careful eg if we ask for some vital signs eg blood pressure that is not self-monitored or retail/pharmacy-provided).
