### ISSUE TITLE
Campaign editor scroll issues

### ISSUE THREAD

**Issue by mverzilli** [instedd/active-monitoring#29]
When entering the campaign editor, the navigation panel seems to be taking the whole screen width initially, which causes the right side of the form to start under the fold. The screen then looks empty. Probably related, when clicking on an element of the sidebar panel, it doesn't scroll to the right section of the form.

**Comment by mverzilli** [comment]
Works ok on master

**Comment by mmuller** [comment]
Working properly in version ae6616b
