### ISSUE TITLE
When user deletes campaign title, autogenerate a new one to avoid empty titles

### ISSUE THREAD

**Issue by mmuller** [instedd/active-monitoring#41]
Reproduce steps:

1. Create a Campaign `C`.
2. Go to edit the Campaign `C`.
3. Remove the title of the Campaign.
4. Observe the Campaigns listing.

Obtained:

- For the Campaign `C` the Title field is empty.

Expected:

- For the Campaign `C` the Title field should show `Untitled Campaign #${campaign.id}`

**Comment by matiasgarciaisaia** [comment]
Done in 50b626d9b6cea93497f00f922376647d4827deeb

**Comment by mmuller** [comment]
Working properly in version ae6616b
