### ISSUE TITLE
Old campaign can be launched if channel is now in use

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/active-monitoring#50]
1 - Create CampaignA, assign free channel
2 - Create CampaignB, assign same channel, launch it
3 - Go back to CampaignA, try to launch it

Expected: you shouldn't be able to launch CampaignA - channel is already in use

Actual: the UI let's you launch CampaignA

At 083592fce1a8c75df607c21ef542db49468980ec

**Comment by mmuller** [comment]
Working properly in version da38261
