### ISSUE TITLE
Menu button doesn't work if the screen width is < 800

### ISSUE THREAD

**Issue by mmuller** [instedd/active-monitoring#64]
Version 2c1feb1

![screen shot 2017-12-28 at 10 48 23 am](https://user-images.githubusercontent.com/518152/34415226-3ed635a0-ebcc-11e7-9955-ba7b538b0983.png)

**Comment by matiasgarciaisaia** [comment]
Fixed via ceb87ee009e0bcdbc42d9b75a47310a337e11dc6

We've removed the button and added a Hamburguer menu on the left with the login options. We've still have to define how/what to show on that right hand menu.

**Comment by mmuller** [comment]
Working properly in version 1d72f67
