### ISSUE TITLE
Empty columns in Subjects listing.

### ISSUE THREAD

**Issue by mmuller** [instedd/active-monitoring#66]
Version: 2c1feb1

If the Subject has no symptoms the `First Call`, `Last Call`, and `Last Successful Call` column are empty.

<img width="1359" alt="screen shot 2017-12-28 at 4 51 15 pm" src="https://user-images.githubusercontent.com/518152/34421660-58e3929e-ebef-11e7-86d6-9d771c8a88cc.png">

**Comment by matiasgarciaisaia** [comment]
Can't repro on version: 0.0.1-dev-0718339 (build 205)

Probably fixed with e8a1223759e505ee4e5f30b42d9de621d2cb1ff4

**Comment by mmuller** [comment]
Working properly in version 1d72f67
