### ISSUE TITLE
Update campaign stats based on mode

### ISSUE THREAD

**Issue by emaraschio** [instedd/active-monitoring#95]
TBD

**Comment by nekron** [comment]
We need to make changes on AIDA to know the current step of the survey. For more information see: https://github.com/instedd/active-monitoring/issues/95

**Comment by emaraschio** [comment]
@nekron  we will need this stats from AIDA or at least the raw data to complete all of the fields

Campaign Performance:
- Cases detected: If at least one answers of survey was yes
- Enrolled callers / Enrolled subjects: Total of subjects with at least one complete survey
- Enrolled subjects per week: A timeline based on day
- Call Performance / Chatbot Performance: Total of: Chats today / Chats last 7 days / Finished chats (Complete all the survey)
- Weekly calls by status / Weekly chats by status: Finished / Not finished
